name: Refresh GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update cache-busting parameter
        shell: bash
        run: |
          VERSION=$(date +%s)

          sed -Ei "s/v=[0-9]+/v=${VERSION}/g" README.md

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "🔄 Refresh GitHub Stats"
            git push
          fi
